### ISSUE TITLE
Different behavior from vue-cli

### ISSUE THREAD

**Issue by bovas85** [nuxt-community/create-nuxt-app#26]
# Expected behavior
Creates a folder named as the project where files are

# Current behavior
It downloads the files in pwd current directory

**Comment by Atinux** [comment]
@egoist is it possible with SAO?

**Comment by egoist** [comment]
It should already work, I suppose.

**Comment by egoist** [comment]
I don't get the question, what does _Creates a folder named as the project where files are_ mean?

**Comment by bovas85** [comment]
pwd
CurrentUser/Desktop
run cli here <!-- 
files are created inside Desktop folder rather than Desktop/projectname

**Comment by egoist** [comment]
Isn't that the expected behavior? 😅

**Comment by egoist** [comment]
hmm it's different in create-nuxt-app, if you don't specify a folder name it will generate in cwd otherwise in the specified folder. It's different from `vue-cli init` but is the same as `yeoman`, we don't need to make them behave in the same way (until @Atinux thinks we should), anyways even `vue-cli init` will be deprecated in vue-cli 3.0

**Comment by Atinux** [comment]
Thanks for your explanations @egoist 

We will keep the current behaviour.

**Comment by bovas85** [comment]
I see, thanks for clarifying
